/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.charges;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        ChargesApp classUnderTest = new ChargesApp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
